// Major worldwide ports
export const WORLD_PORTS = [
  // Middle East
  "Jebel Ali, UAE",
  "Khalifa Port, UAE",
  "Fujairah, UAE",
  "Sharjah, UAE",
  "Aqaba, Jordan",
  "Jeddah, Saudi Arabia",
  "Dammam, Saudi Arabia",
  "Jubail, Saudi Arabia",
  "Salalah, Oman",
  "Sohar, Oman",
  "Hamad Port, Qatar",
  "Mina Salman, Bahrain",
  "Shuwaikh, Kuwait",
  "Bandar Abbas, Iran",
  
  // Asia
  "Shanghai, China",
  "Singapore, Singapore",
  "Ningbo-Zhoushan, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Qingdao, China",
  "Busan, South Korea",
  "Hong Kong, China",
  "Tianjin, China",
  "Xiamen, China",
  "Kaohsiung, Taiwan",
  "Port Klang, Malaysia",
  "Tanjung Pelepas, Malaysia",
  "Laem Chabang, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Hai Phong, Vietnam",
  "Jakarta, Indonesia",
  "Colombo, Sri Lanka",
  "Chennai, India",
  "Nhava Sheva, India",
  "Mundra, India",
  "Karachi, Pakistan",
  "Manila, Philippines",
  "Tokyo, Japan",
  "Yokohama, Japan",
  "Kobe, Japan",
  "Nagoya, Japan",
  
  // Europe
  "Rotterdam, Netherlands",
  "Antwerp, Belgium",
  "Hamburg, Germany",
  "Bremerhaven, Germany",
  "Valencia, Spain",
  "Algeciras, Spain",
  "Barcelona, Spain",
  "Piraeus, Greece",
  "Genoa, Italy",
  "Gioia Tauro, Italy",
  "Felixstowe, UK",
  "Southampton, UK",
  "London Gateway, UK",
  "Le Havre, France",
  "Marseille, France",
  "Gdansk, Poland",
  "Gothenburg, Sweden",
  "Koper, Slovenia",
  "Constanta, Romania",
  
  // Americas
  "Los Angeles, USA",
  "Long Beach, USA",
  "New York/New Jersey, USA",
  "Savannah, USA",
  "Houston, USA",
  "Seattle, USA",
  "Oakland, USA",
  "Miami, USA",
  "Charleston, USA",
  "Norfolk, USA",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Prince Rupert, Canada",
  "Santos, Brazil",
  "Buenos Aires, Argentina",
  "Callao, Peru",
  "Cartagena, Colombia",
  "Manzanillo, Mexico",
  "Lazaro Cardenas, Mexico",
  "Balboa, Panama",
  "Colon, Panama",
  
  // Africa
  "Port Said, Egypt",
  "Alexandria, Egypt",
  "Tangier Med, Morocco",
  "Durban, South Africa",
  "Cape Town, South Africa",
  "Mombasa, Kenya",
  "Dar es Salaam, Tanzania",
  "Lagos (Apapa), Nigeria",
  "Djibouti, Djibouti",
  
  // Oceania
  "Melbourne, Australia",
  "Sydney, Australia",
  "Brisbane, Australia",
  "Auckland, New Zealand",
  "Port Hedland, Australia",
] as const;

export const INCOTERMS = [
  { value: "EXW", label: "EXW - Ex Works" },
  { value: "FCA", label: "FCA - Free Carrier" },
  { value: "CPT", label: "CPT - Carriage Paid To" },
  { value: "CIP", label: "CIP - Carriage and Insurance Paid To" },
  { value: "DAP", label: "DAP - Delivered at Place" },
  { value: "DPU", label: "DPU - Delivered at Place Unloaded" },
  { value: "DDP", label: "DDP - Delivered Duty Paid" },
  { value: "FAS", label: "FAS - Free Alongside Ship" },
  { value: "FOB", label: "FOB - Free on Board" },
  { value: "CFR", label: "CFR - Cost and Freight" },
  { value: "CIF", label: "CIF - Cost, Insurance and Freight" },
] as const;

export type Incoterm = typeof INCOTERMS[number]['value'];
