// Major worldwide sea ports
export const WORLD_PORTS = [
  // Middle East
  "Jebel Ali, UAE",
  "Khalifa Port, UAE",
  "Fujairah, UAE",
  "Sharjah, UAE",
  "Abu Dhabi (Mina Zayed), UAE",
  "Aqaba, Jordan",
  "Jeddah, Saudi Arabia",
  "Dammam, Saudi Arabia",
  "Jubail, Saudi Arabia",
  "Yanbu, Saudi Arabia",
  "Salalah, Oman",
  "Sohar, Oman",
  "Muscat, Oman",
  "Hamad Port, Qatar",
  "Mina Salman, Bahrain",
  "Shuwaikh, Kuwait",
  "Shuaiba, Kuwait",
  "Bandar Abbas, Iran",
  "Umm Qasr, Iraq",
  "Basra, Iraq",
  
  // Asia - China
  "Shanghai, China",
  "Ningbo-Zhoushan, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Qingdao, China",
  "Hong Kong, China",
  "Tianjin, China",
  "Xiamen, China",
  "Dalian, China",
  "Taicang, China",
  "Lianyungang, China",
  "Nanjing, China",
  "Fuzhou, China",
  
  // Asia - Rest
  "Singapore, Singapore",
  "Busan, South Korea",
  "Incheon, South Korea",
  "Kaohsiung, Taiwan",
  "Keelung, Taiwan",
  "Port Klang, Malaysia",
  "Tanjung Pelepas, Malaysia",
  "Penang, Malaysia",
  "Laem Chabang, Thailand",
  "Bangkok, Thailand",
  "Ho Chi Minh City, Vietnam",
  "Hai Phong, Vietnam",
  "Da Nang, Vietnam",
  "Tanjung Priok, Indonesia",
  "Surabaya, Indonesia",
  "Colombo, Sri Lanka",
  "Chennai, India",
  "Nhava Sheva (JNPT), India",
  "Mundra, India",
  "Kandla, India",
  "Cochin, India",
  "Visakhapatnam, India",
  "Kolkata, India",
  "Karachi, Pakistan",
  "Port Qasim, Pakistan",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Tokyo, Japan",
  "Yokohama, Japan",
  "Kobe, Japan",
  "Nagoya, Japan",
  "Osaka, Japan",
  
  // Europe
  "Rotterdam, Netherlands",
  "Antwerp, Belgium",
  "Zeebrugge, Belgium",
  "Hamburg, Germany",
  "Bremerhaven, Germany",
  "Valencia, Spain",
  "Algeciras, Spain",
  "Barcelona, Spain",
  "Bilbao, Spain",
  "Piraeus, Greece",
  "Thessaloniki, Greece",
  "Genoa, Italy",
  "Gioia Tauro, Italy",
  "Trieste, Italy",
  "Livorno, Italy",
  "La Spezia, Italy",
  "Naples, Italy",
  "Felixstowe, UK",
  "Southampton, UK",
  "London Gateway, UK",
  "Liverpool, UK",
  "Le Havre, France",
  "Marseille, France",
  "Dunkirk, France",
  "Gdansk, Poland",
  "Gdynia, Poland",
  "Gothenburg, Sweden",
  "Koper, Slovenia",
  "Constanta, Romania",
  "Izmir, Turkey",
  "Mersin, Turkey",
  "Istanbul (Ambarli), Turkey",
  "Lisbon, Portugal",
  "Leixoes, Portugal",
  "Sines, Portugal",
  
  // Americas - North
  "Los Angeles, USA",
  "Long Beach, USA",
  "New York/New Jersey, USA",
  "Savannah, USA",
  "Houston, USA",
  "Seattle, USA",
  "Oakland, USA",
  "Miami, USA",
  "Charleston, USA",
  "Norfolk, USA",
  "Baltimore, USA",
  "Philadelphia, USA",
  "New Orleans, USA",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Prince Rupert, Canada",
  "Toronto, Canada",
  "Halifax, Canada",
  
  // Americas - Central & South
  "Santos, Brazil",
  "Paranagua, Brazil",
  "Rio Grande, Brazil",
  "Buenos Aires, Argentina",
  "Callao, Peru",
  "Cartagena, Colombia",
  "Buenaventura, Colombia",
  "Manzanillo, Mexico",
  "Lazaro Cardenas, Mexico",
  "Veracruz, Mexico",
  "Altamira, Mexico",
  "Balboa, Panama",
  "Colon, Panama",
  "San Antonio, Chile",
  "Valparaiso, Chile",
  "Puerto Cabello, Venezuela",
  "Montevideo, Uruguay",
  "Guayaquil, Ecuador",
  
  // Africa
  "Port Said, Egypt",
  "Alexandria, Egypt",
  "Damietta, Egypt",
  "Tangier Med, Morocco",
  "Casablanca, Morocco",
  "Durban, South Africa",
  "Cape Town, South Africa",
  "Mombasa, Kenya",
  "Dar es Salaam, Tanzania",
  "Lagos (Apapa), Nigeria",
  "Tema, Ghana",
  "Abidjan, Ivory Coast",
  "Djibouti, Djibouti",
  "Luanda, Angola",
  "Nacala, Mozambique",
  "Maputo, Mozambique",
  "Port Louis, Mauritius",
  "Beira, Mozambique",
  "Walvis Bay, Namibia",
  "Pointe Noire, Congo",
  
  // Oceania
  "Melbourne, Australia",
  "Sydney, Australia",
  "Brisbane, Australia",
  "Fremantle, Australia",
  "Auckland, New Zealand",
  "Tauranga, New Zealand",
  "Port Hedland, Australia",
  "Adelaide, Australia",
] as const;

// Major worldwide cargo airports (IATA codes)
export const WORLD_AIRPORTS = [
  // Middle East
  "Dubai (DXB), UAE",
  "Sharjah (SHJ), UAE",
  "Abu Dhabi (AUH), UAE",
  "Al Maktoum (DWC), UAE",
  "Amman Queen Alia (AMM), Jordan",
  "Jeddah (JED), Saudi Arabia",
  "Riyadh (RUH), Saudi Arabia",
  "Dammam (DMM), Saudi Arabia",
  "Doha (DOH), Qatar",
  "Kuwait (KWI), Kuwait",
  "Bahrain (BAH), Bahrain",
  "Muscat (MCT), Oman",
  "Tehran (IKA), Iran",
  "Baghdad (BGW), Iraq",
  
  // Asia - China & Hong Kong
  "Hong Kong (HKG), China",
  "Shanghai Pudong (PVG), China",
  "Guangzhou (CAN), China",
  "Beijing (PEK), China",
  "Shenzhen (SZX), China",
  "Zhengzhou (CGO), China",
  "Chengdu (CTU), China",
  "Chongqing (CKG), China",
  
  // Asia - Rest
  "Singapore (SIN), Singapore",
  "Incheon (ICN), South Korea",
  "Tokyo Narita (NRT), Japan",
  "Tokyo Haneda (HND), Japan",
  "Osaka Kansai (KIX), Japan",
  "Taipei (TPE), Taiwan",
  "Kaohsiung (KHH), Taiwan",
  "Bangkok (BKK), Thailand",
  "Kuala Lumpur (KUL), Malaysia",
  "Mumbai (BOM), India",
  "Delhi (DEL), India",
  "Chennai (MAA), India",
  "Bengaluru (BLR), India",
  "Colombo (CMB), Sri Lanka",
  "Karachi (KHI), Pakistan",
  "Lahore (LHE), Pakistan",
  "Manila (MNL), Philippines",
  "Cebu (CEB), Philippines",
  "Jakarta (CGK), Indonesia",
  "Surabaya (SUB), Indonesia",
  "Ho Chi Minh (SGN), Vietnam",
  "Hanoi (HAN), Vietnam",
  
  // Europe
  "Frankfurt (FRA), Germany",
  "Amsterdam (AMS), Netherlands",
  "London Heathrow (LHR), UK",
  "Paris CDG (CDG), France",
  "Brussels (BRU), Belgium",
  "Liege (LGG), Belgium",
  "Milan Malpensa (MXP), Italy",
  "Zurich (ZRH), Switzerland",
  "Luxembourg (LUX), Luxembourg",
  "Leipzig (LEJ), Germany",
  "Munich (MUC), Germany",
  "Cologne (CGN), Germany",
  "Copenhagen (CPH), Denmark",
  "Madrid (MAD), Spain",
  "Barcelona (BCN), Spain",
  "Vienna (VIE), Austria",
  "Istanbul (IST), Turkey",
  "Moscow (SVO), Russia",
  "Warsaw (WAW), Poland",
  
  // Americas
  "Los Angeles (LAX), USA",
  "Miami (MIA), USA",
  "New York JFK (JFK), USA",
  "Chicago O'Hare (ORD), USA",
  "Atlanta (ATL), USA",
  "Dallas (DFW), USA",
  "Houston (IAH), USA",
  "Memphis (MEM), USA",
  "Louisville (SDF), USA",
  "Anchorage (ANC), USA",
  "Toronto (YYZ), Canada",
  "Vancouver (YVR), Canada",
  "Mexico City (MEX), Mexico",
  "Guadalajara (GDL), Mexico",
  "Sao Paulo (GRU), Brazil",
  "Campinas (VCP), Brazil",
  "Bogota (BOG), Colombia",
  "Santiago (SCL), Chile",
  "Lima (LIM), Peru",
  "Buenos Aires (EZE), Argentina",
  
  // Africa
  "Johannesburg (JNB), South Africa",
  "Cairo (CAI), Egypt",
  "Nairobi (NBO), Kenya",
  "Lagos (LOS), Nigeria",
  "Addis Ababa (ADD), Ethiopia",
  "Casablanca (CMN), Morocco",
  "Cape Town (CPT), South Africa",
  
  // Oceania
  "Sydney (SYD), Australia",
  "Melbourne (MEL), Australia",
  "Auckland (AKL), New Zealand",
] as const;

export const INCOTERMS = [
  { value: "EXW", label: "EXW - Ex Works" },
  { value: "FCA", label: "FCA - Free Carrier" },
  { value: "CPT", label: "CPT - Carriage Paid To" },
  { value: "CIP", label: "CIP - Carriage and Insurance Paid To" },
  { value: "DAP", label: "DAP - Delivered at Place" },
  { value: "DPU", label: "DPU - Delivered at Place Unloaded" },
  { value: "DDP", label: "DDP - Delivered Duty Paid" },
  { value: "FAS", label: "FAS - Free Alongside Ship" },
  { value: "FOB", label: "FOB - Free on Board" },
  { value: "CFR", label: "CFR - Cost and Freight" },
  { value: "CIF", label: "CIF - Cost, Insurance and Freight" },
] as const;

export type Incoterm = typeof INCOTERMS[number]['value'];

// Helper to get the appropriate list based on mode of transport
export function getLocationOptions(mode: string): readonly string[] {
  if (mode === 'air') {
    return WORLD_AIRPORTS;
  }
  return WORLD_PORTS;
}
